import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { HeroSection } from "@/components/hero-section";
import { ThemeProvider } from "@/components/theme-provider";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${outfit.variable} ${geistMono.variable} antialiased font-sans`}>
				<ThemeProvider>
					<Header />
					<main className="flex min-h-screen flex-col items-center bg-background px-4 pt-12">
						<HeroSection />
						{children}
					</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
